# Model parameters
batch_size: 100  # independent sequences processed in parallel
context_len: 256  # maximum token context length
n_embd: 256  # linear layers size
n_head: 8  # parallel attention heads
n_layer: 6  # attention blocks in sequence
dropout: 0.15

# Training parameters
learning_rate: 0.002
start_iter: 0
max_iters: 2000
eval_interval: 100
save_interval: 100
eval_iters: 30
texts_sample_frac: 1.0
split_frac: 0.8

# Other parameters
path_input: "data/df_full_v0.pq"
path_tokenizer: "artifacts/tokenizers/mix_ptbr_4096_v1.joblib"
name: "v12"
# path_load_model: "artifacts/checkpoints/king_v1_1999.pth"
path_save_model: "artifacts/checkpoints/mix_v1"
path_generate_output: "output/mix_v1.txt"
n_tokens_generate: 1000
context: "Escrevo sob efeito de horrores inimaginaveis"
