# Model parameters
batch_size: 10  # independent sequences processed in parallel
context_len: 10  # maximum token context length
n_embd: 10  # linear layers size
n_feed_forward: 100
n_head: 2  # parallel attention heads
n_layer: 1  # attention blocks in sequence
dropout: 0.0

# Optimizer parameters
grad_accum_steps: 1
learning_rate: 0.01
betas: [0.9, 0.98]
eps: 0.000_000_001
weight_decay: 0.01
dynamic_lr: false
warmup_steps: 1000 # 4000

# Iteration loop parameters
start_iter: 0
max_iters: 2000
eval_interval: 50
save_interval: 50
eval_iters: 20
texts_sample_frac: 1.0
split_frac: 0.85
n_checkpoints_keep: 5

# Generation parameters
top_k: 30
temperature: 0.7

# Paths
path_tokenizer: "artifacts/tokenizers/gpt2_ptbr_50k_v2"

path_input: "data/df_full_encoded_v21.pq"
# path_input_encoded: "data/df_full_encoded_v20.pq"
# encode_input: true  # false

path_models: "models"
name: "v22_test"
n_tokens_generate: 600
context: "Escrevo sob efeito de horrores inimagináveis."
# path_load_model: "/kaggle/input/v18-colab/4600.pth"
# path_load_optim: "models/v18_test/checkpoints/optim.pth"
# dummy: true
tqdm_train: true
tqdm_eval: true